version: "3.3"

services:
  todo-management:
    container_name: todo-management
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    env_file: .env.local
